// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Note struct {
	ID        int64
	Title     string
	Body      string
	Preview   string
	Pinned    int64
	CreatedAt int64
	UpdatedAt int64
	DeletedAt sql.NullInt64
}
