// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, body, preview, pinned, created_at, updated_at)
VALUES ('', '', '', 0, ?, ?)
RETURNING id, title, body, pinned, created_at, updated_at
`

type CreateNoteParams struct {
	CreatedAt int64
	UpdatedAt int64
}

type CreateNoteRow struct {
	ID        int64
	Title     string
	Body      string
	Pinned    int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.CreatedAt, arg.UpdatedAt)
	var i CreateNoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, title, body, pinned, created_at, updated_at
FROM notes
WHERE id = ? AND deleted_at IS NULL
`

type GetNoteRow struct {
	ID        int64
	Title     string
	Body      string
	Pinned    int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) GetNote(ctx context.Context, id int64) (GetNoteRow, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i GetNoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNotes = `-- name: ListActiveNotes :many
SELECT id, title, preview, pinned, updated_at
FROM notes
WHERE deleted_at IS NULL
ORDER BY pinned DESC, updated_at DESC
`

type ListActiveNotesRow struct {
	ID        int64
	Title     string
	Preview   string
	Pinned    int64
	UpdatedAt int64
}

func (q *Queries) ListActiveNotes(ctx context.Context) ([]ListActiveNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNotesRow
	for rows.Next() {
		var i ListActiveNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Preview,
			&i.Pinned,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveNotesForExport = `-- name: ListActiveNotesForExport :many
SELECT id, title, body
FROM notes
WHERE deleted_at IS NULL
ORDER BY updated_at DESC
`

type ListActiveNotesForExportRow struct {
	ID    int64
	Title string
	Body  string
}

func (q *Queries) ListActiveNotesForExport(ctx context.Context) ([]ListActiveNotesForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNotesForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNotesForExportRow
	for rows.Next() {
		var i ListActiveNotesForExportRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllNotes = `-- name: ListAllNotes :many
SELECT id, title, preview, pinned, updated_at
FROM notes
ORDER BY pinned DESC, updated_at DESC
`

type ListAllNotesRow struct {
	ID        int64
	Title     string
	Preview   string
	Pinned    int64
	UpdatedAt int64
}

func (q *Queries) ListAllNotes(ctx context.Context) ([]ListAllNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllNotesRow
	for rows.Next() {
		var i ListAllNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Preview,
			&i.Pinned,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeNote = `-- name: PurgeNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) PurgeNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeNote, id)
	return err
}

const restoreNote = `-- name: RestoreNote :exec
UPDATE notes SET deleted_at = NULL WHERE id = ?
`

func (q *Queries) RestoreNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreNote, id)
	return err
}

const togglePin = `-- name: TogglePin :exec
UPDATE notes
SET pinned = ?
WHERE id = ? AND deleted_at IS NULL
`

type TogglePinParams struct {
	Pinned int64
	ID     int64
}

func (q *Queries) TogglePin(ctx context.Context, arg TogglePinParams) error {
	_, err := q.db.ExecContext(ctx, togglePin, arg.Pinned, arg.ID)
	return err
}

const trashNote = `-- name: TrashNote :exec
UPDATE notes SET deleted_at = ? WHERE id = ?
`

type TrashNoteParams struct {
	DeletedAt sql.NullInt64
	ID        int64
}

func (q *Queries) TrashNote(ctx context.Context, arg TrashNoteParams) error {
	_, err := q.db.ExecContext(ctx, trashNote, arg.DeletedAt, arg.ID)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET body = ?, title = ?, preview = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, title, preview, pinned, updated_at
`

type UpdateNoteParams struct {
	Body      string
	Title     string
	Preview   string
	UpdatedAt int64
	ID        int64
}

type UpdateNoteRow struct {
	ID        int64
	Title     string
	Preview   string
	Pinned    int64
	UpdatedAt int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (UpdateNoteRow, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Body,
		arg.Title,
		arg.Preview,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateNoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Preview,
		&i.Pinned,
		&i.UpdatedAt,
	)
	return i, err
}
