// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote():Promise<main.Note>;

export function ExportAll():Promise<void>;

export function ExportNote(arg1:number):Promise<void>;

export function GetNote(arg1:number):Promise<main.Note>;

export function ListNotes(arg1:boolean):Promise<Array<main.NoteSummary>>;

export function PurgeNote(arg1:number):Promise<void>;

export function RestoreNote(arg1:number):Promise<void>;

export function TogglePin(arg1:number,arg2:boolean):Promise<void>;

export function TrashNote(arg1:number):Promise<void>;

export function UpdateNote(arg1:number,arg2:string):Promise<main.NoteSummary>;
