// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote() {
  return window['go']['main']['App']['CreateNote']();
}

export function ExportAll() {
  return window['go']['main']['App']['ExportAll']();
}

export function ExportNote(arg1) {
  return window['go']['main']['App']['ExportNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function PurgeNote(arg1) {
  return window['go']['main']['App']['PurgeNote'](arg1);
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function TogglePin(arg1, arg2) {
  return window['go']['main']['App']['TogglePin'](arg1, arg2);
}

export function TrashNote(arg1) {
  return window['go']['main']['App']['TrashNote'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
